package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "PainAndGain_2017")
public class Account implements java.io.Serializable {

	private int maAc;
	private String userName;
	private String pass;
	private int trangThai;

	public Account() {
	}

	public Account(int maAc) {
		this.maAc = maAc;
	}

	public Account(int maAc, String userName, String pass, int trangThai) {
		this.maAc = maAc;
		this.userName = userName;
		this.pass = pass;
		this.trangThai= trangThai;
	}

	@Id

	@Column(name = "MA_AC", unique = true, nullable = false)
	public int getMaAc() {
		return this.maAc;
	}

	public void setMaAc(int maAc) {
		this.maAc = maAc;
	}

	@Column(name = "USER_NAME", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASS", length = 20)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}
	
	@Column(name = "TRANG_THAI")
	public int getTrangThai() {
		return trangThai;
	}

	public void setTrangThai(int trangThai) {
		this.trangThai = trangThai;
	}
	

}
