package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaLam generated by hbm2java
 */
@Entity
@Table(name = "ca_lam", catalog = "PainAndGain_2017")
public class CaLam implements java.io.Serializable {

	private Integer maCa;
	private String gioBatDau;
	private String gioKetThuc;
	private int luongGio;

	public CaLam() {
	}

	public CaLam(String gioBatDau, String gioKetThuc, int luongGio) {
		this.gioBatDau = gioBatDau;
		this.gioKetThuc = gioKetThuc;
		this.luongGio = luongGio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_CA", unique = true, nullable = false)
	public Integer getMaCa() {
		return this.maCa;
	}

	public void setMaCa(Integer maCa) {
		this.maCa = maCa;
	}

	
	@Column(name = "GIO_BAT_DAU", nullable = false, length = 8)
	public String getGioBatDau() {
		return this.gioBatDau;
	}

	public void setGioBatDau(String gioBatDau) {
		this.gioBatDau = gioBatDau;
	}

	
	@Column(name = "GIO_KET_THUC", nullable = false, length = 8)
	public String getGioKetThuc() {
		return this.gioKetThuc;
	}

	public void setGioKetThuc(String gioKetThuc) {
		this.gioKetThuc = gioKetThuc;
	}

	@Column(name = "LUONG_GIO", nullable = false)
	public int getLuongGio() {
		return this.luongGio;
	}

	public void setLuongGio(int luongGio) {
		this.luongGio = luongGio;
	}

}
