package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChamCong generated by hbm2java
 */
@Entity
@Table(name = "cham_cong", catalog = "PainAndGain_2017")
public class ChamCong implements java.io.Serializable {

	private Integer maCc;
	private int maNv;
	private String gioBatDau;
	private String gioKetThuc;
	private String ngay;
	private Integer maCa;

	public ChamCong() {
	}

	public ChamCong(int maNv, String gioBatDau, String gioKetThuc, String ngay) {
		this.maNv = maNv;
		this.gioBatDau = gioBatDau;
		this.gioKetThuc = gioKetThuc;
		this.ngay = ngay;
	}

	public ChamCong(int maNv, String gioBatDau, String gioKetThuc, String ngay, Integer maCa) {
		this.maNv = maNv;
		this.gioBatDau = gioBatDau;
		this.gioKetThuc = gioKetThuc;
		this.ngay = ngay;
		this.maCa = maCa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_CC", unique = true, nullable = false)
	public Integer getMaCc() {
		return this.maCc;
	}

	public void setMaCc(Integer maCc) {
		this.maCc = maCc;
	}

	@Column(name = "MA_NV", nullable = false)
	public int getMaNv() {
		return this.maNv;
	}

	public void setMaNv(int maNv) {
		this.maNv = maNv;
	}

	
	@Column(name = "GIO_BAT_DAU", nullable = false, length = 8)
	public String getGioBatDau() {
		return this.gioBatDau;
	}

	public void setGioBatDau(String gioBatDau) {
		this.gioBatDau = gioBatDau;
	}

	
	@Column(name = "GIO_KET_THUC", nullable = false, length = 8)
	public String getGioKetThuc() {
		return this.gioKetThuc;
	}

	public void setGioKetThuc(String gioKetThuc) {
		this.gioKetThuc = gioKetThuc;
	}

	
	@Column(name = "NGAY", nullable = false, length = 10)
	public String getNgay() {
		return this.ngay;
	}

	public void setNgay(String ngay) {
		this.ngay = ngay;
	}

	@Column(name = "MA_CA")
	public Integer getMaCa() {
		return this.maCa;
	}

	public void setMaCa(Integer maCa) {
		this.maCa = maCa;
	}

}
