package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChiTietHoaDon generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_hoa_don", catalog = "PainAndGain_2017")
public class ChiTietHoaDon implements java.io.Serializable {

	private Integer maCtHd;
	private Integer maHd;
	private Integer maSp;
	private int soLuong;
	private Integer giamGia;
	private Boolean laPhanTram;

	public ChiTietHoaDon() {
	}

	public ChiTietHoaDon(int soLuong) {
		this.soLuong = soLuong;
	}

	public ChiTietHoaDon(Integer maHd, Integer maSp, int soLuong, Integer giamGia, Boolean laPhanTram) {
		this.maHd = maHd;
		this.maSp = maSp;
		this.soLuong = soLuong;
		this.giamGia = giamGia;
		this.laPhanTram = laPhanTram;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_CT_HD", unique = true, nullable = false)
	public Integer getMaCtHd() {
		return this.maCtHd;
	}

	public void setMaCtHd(Integer maCtHd) {
		this.maCtHd = maCtHd;
	}

	@Column(name = "MA_HD")
	public Integer getMaHd() {
		return this.maHd;
	}

	public void setMaHd(Integer maHd) {
		this.maHd = maHd;
	}

	@Column(name = "MA_SP")
	public Integer getMaSp() {
		return this.maSp;
	}

	public void setMaSp(Integer maSp) {
		this.maSp = maSp;
	}

	@Column(name = "SO_LUONG", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "GIAM_GIA")
	public Integer getGiamGia() {
		return this.giamGia;
	}

	public void setGiamGia(Integer giamGia) {
		this.giamGia = giamGia;
	}

	@Column(name = "LA_PHAN_TRAM")
	public Boolean getLaPhanTram() {
		return this.laPhanTram;
	}

	public void setLaPhanTram(Boolean laPhanTram) {
		this.laPhanTram = laPhanTram;
	}

}
