package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChiTietPhieuNhap generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_phieu_nhap", catalog = "PainAndGain_2017")
public class ChiTietPhieuNhap implements java.io.Serializable {

	private Integer maCtPn;
	private Integer maPn;
	private Integer maSp;
	private int donGia;
	private int soLuong;
	private Integer maNcc;

	public ChiTietPhieuNhap() {
	}

	public ChiTietPhieuNhap(int donGia, int soLuong) {
		this.donGia = donGia;
		this.soLuong = soLuong;
	}

	public ChiTietPhieuNhap(Integer maPn, Integer maSp, int donGia, int soLuong, Integer maNcc) {
		this.maPn = maPn;
		this.maSp = maSp;
		this.donGia = donGia;
		this.soLuong = soLuong;
		this.maNcc = maNcc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_CT_PN", unique = true, nullable = false)
	public Integer getMaCtPn() {
		return this.maCtPn;
	}

	public void setMaCtPn(Integer maCtPn) {
		this.maCtPn = maCtPn;
	}

	@Column(name = "MA_PN")
	public Integer getMaPn() {
		return this.maPn;
	}

	public void setMaPn(Integer maPn) {
		this.maPn = maPn;
	}

	@Column(name = "MA_SP")
	public Integer getMaSp() {
		return this.maSp;
	}

	public void setMaSp(Integer maSp) {
		this.maSp = maSp;
	}

	@Column(name = "DON_GIA", nullable = false)
	public int getDonGia() {
		return this.donGia;
	}

	public void setDonGia(int donGia) {
		this.donGia = donGia;
	}

	@Column(name = "SO_LUONG", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "MA_NCC")
	public Integer getMaNcc() {
		return this.maNcc;
	}

	public void setMaNcc(Integer maNcc) {
		this.maNcc = maNcc;
	}

}
