package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DanhMuc generated by hbm2java
 */
@Entity
@Table(name = "danh_muc", catalog = "PainAndGain_2017")
public class DanhMuc implements java.io.Serializable {

	private Integer maDm;
	private String tenDm;

	public DanhMuc() {
	}

	public DanhMuc(String tenDm) {
		this.tenDm = tenDm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_DM", unique = true, nullable = false)
	public Integer getMaDm() {
		return this.maDm;
	}

	public void setMaDm(Integer maDm) {
		this.maDm = maDm;
	}

	@Column(name = "TEN_DM", nullable = false, length = 200)
	public String getTenDm() {
		return this.tenDm;
	}

	public void setTenDm(String tenDm) {
		this.tenDm = tenDm;
	}

}
