package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "hoa_don", catalog = "PainAndGain_2017")
public class HoaDon implements java.io.Serializable {

	private Integer maHd;
	private String ngayLap;
	private Integer maKh;

	public HoaDon() {
	}

	public HoaDon(String ngayLap, Integer maKh) {
		this.ngayLap = ngayLap;
		this.maKh = maKh;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_HD", unique = true, nullable = false)
	public Integer getMaHd() {
		return this.maHd;
	}

	public void setMaHd(Integer maHd) {
		this.maHd = maHd;
	}

	
	@Column(name = "NGAY_LAP", length = 10)
	public String getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(String ngayLap) {
		this.ngayLap = ngayLap;
	}

	@Column(name = "MA_KH")
	public Integer getMaKh() {
		return this.maKh;
	}

	public void setMaKh(Integer maKh) {
		this.maKh = maKh;
	}

}
