package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "khach_hang", catalog = "PainAndGain_2017")
public class KhachHang implements java.io.Serializable {

	private Integer maKh;
	private String tenKh;
	private String diaChi;
	private String soDt;

	public KhachHang() {
	}

	public KhachHang(String tenKh) {
		this.tenKh = tenKh;
	}

	public KhachHang(String tenKh, String diaChi, String soDt) {
		this.tenKh = tenKh;
		this.diaChi = diaChi;
		this.soDt = soDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_KH", unique = true, nullable = false)
	public Integer getMaKh() {
		return this.maKh;
	}

	public void setMaKh(Integer maKh) {
		this.maKh = maKh;
	}

	@Column(name = "TEN_KH", nullable = false, length = 200)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "DIA_CHI", length = 300)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SO_DT", length = 12)
	public String getSoDt() {
		return this.soDt;
	}

	public void setSoDt(String soDt) {
		this.soDt = soDt;
	}

}
