package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoaiSp generated by hbm2java
 */
@Entity
@Table(name = "loai_sp", catalog = "PainAndGain_2017")
public class LoaiSp implements java.io.Serializable {

	private Integer maLoai;
	private String tenLoai;
	private Integer maDm;

	public LoaiSp() {
	}

	public LoaiSp(String tenLoai) {
		this.tenLoai = tenLoai;
	}

	public LoaiSp(String tenLoai, Integer maDm) {
		this.tenLoai = tenLoai;
		this.maDm = maDm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_LOAI", unique = true, nullable = false)
	public Integer getMaLoai() {
		return this.maLoai;
	}

	public void setMaLoai(Integer maLoai) {
		this.maLoai = maLoai;
	}

	@Column(name = "TEN_LOAI", nullable = false, length = 300)
	public String getTenLoai() {
		return this.tenLoai;
	}

	public void setTenLoai(String tenLoai) {
		this.tenLoai = tenLoai;
	}

	@Column(name = "MA_DM")
	public Integer getMaDm() {
		return this.maDm;
	}

	public void setMaDm(Integer maDm) {
		this.maDm = maDm;
	}

}
