package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NhaccSanpham generated by hbm2java
 */
@Entity
@Table(name = "nhacc_sanpham", catalog = "PainAndGain_2017")
public class NhaccSanpham implements java.io.Serializable {

	private Integer maNhaccSanpham;
	private Integer maNcc;
	private Integer maSp;

	public NhaccSanpham() {
	}

	public NhaccSanpham(Integer maNcc, Integer maSp) {
		this.maNcc = maNcc;
		this.maSp = maSp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_NHACC_SANPHAM", unique = true, nullable = false)
	public Integer getMaNhaccSanpham() {
		return this.maNhaccSanpham;
	}

	public void setMaNhaccSanpham(Integer maNhaccSanpham) {
		this.maNhaccSanpham = maNhaccSanpham;
	}

	@Column(name = "MA_NCC")
	public Integer getMaNcc() {
		return this.maNcc;
	}

	public void setMaNcc(Integer maNcc) {
		this.maNcc = maNcc;
	}

	@Column(name = "MA_SP")
	public Integer getMaSp() {
		return this.maSp;
	}

	public void setMaSp(Integer maSp) {
		this.maSp = maSp;
	}

}
