package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NhaCc generated by hbm2java
 */
@Entity
@Table(name = "nha_cc", catalog = "PainAndGain_2017")
public class NhaCc implements java.io.Serializable {

	private Integer maNcc;
	private String tenNcc;
	private String diaChi;
	private String soDt;

	public NhaCc() {
	}

	public NhaCc(String tenNcc, String soDt) {
		this.tenNcc = tenNcc;
		this.soDt = soDt;
	}

	public NhaCc(String tenNcc, String diaChi, String soDt) {
		this.tenNcc = tenNcc;
		this.diaChi = diaChi;
		this.soDt = soDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_NCC", unique = true, nullable = false)
	public Integer getMaNcc() {
		return this.maNcc;
	}

	public void setMaNcc(Integer maNcc) {
		this.maNcc = maNcc;
	}

	@Column(name = "TEN_NCC", nullable = false, length = 300)
	public String getTenNcc() {
		return this.tenNcc;
	}

	public void setTenNcc(String tenNcc) {
		this.tenNcc = tenNcc;
	}

	@Column(name = "DIA_CHI", length = 300)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "SO_DT", nullable = false, length = 12)
	public String getSoDt() {
		return this.soDt;
	}

	public void setSoDt(String soDt) {
		this.soDt = soDt;
	}

}
