package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien", catalog = "PainAndGain_2017")
public class NhanVien implements java.io.Serializable {

	private Integer maNv;
	private String tenNv;
	private int gioiTinh;
	private String diaChi;
	private String ngayVaoLam;

	public NhanVien() {
	}

	public NhanVien(int maNv,String tenNv, int gioiTinh, String diaChi, String ngayVaoLam) {
		this.maNv = maNv;
		this.tenNv = tenNv;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.ngayVaoLam = ngayVaoLam;
	}

	public NhanVien(String tenNv, int gioiTinh, String diaChi, String ngayVaoLam) {
		this.tenNv = tenNv;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.ngayVaoLam = ngayVaoLam;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_NV", unique = true, nullable = false)
	public Integer getMaNv() {
		return this.maNv;
	}

	public void setMaNv(Integer maNv) {
		this.maNv = maNv;
	}

	@Column(name = "TEN_NV", nullable = false, length = 100)
	public String getTenNv() {
		return this.tenNv;
	}

	public void setTenNv(String tenNv) {
		this.tenNv = tenNv;
	}

	@Column(name = "GIOI_TINH")
	public int getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DIA_CHI", length = 300)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	
	@Column(name = "NGAY_VAO_LAM", length = 10)
	public String getNgayVaoLam() {
		return this.ngayVaoLam;
	}

	public void setNgayVaoLam(String ngayVaoLam) {
		this.ngayVaoLam = ngayVaoLam;
	}

}
