package model;
// Generated Nov 27, 2017 10:35:36 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhieuNhap generated by hbm2java
 */
@Entity
@Table(name = "phieu_nhap", catalog = "PainAndGain_2017")
public class PhieuNhap implements java.io.Serializable {

	private Integer maPn;
	private String ngayLap;

	public PhieuNhap() {
	}

	public PhieuNhap(String ngayLap) {
		this.ngayLap = ngayLap;
	}
	public PhieuNhap(Integer maPn,String ngayLap) {
		this.maPn= maPn;
		this.ngayLap = ngayLap;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MA_PN", unique = true, nullable = false)
	public Integer getMaPn() {
		return this.maPn;
	}

	public void setMaPn(Integer maPn) {
		this.maPn = maPn;
	}

	
	@Column(name = "NGAY_LAP", nullable = false, length = 10)
	public String getNgayLap() {
		return this.ngayLap;
	}

	public void setNgayLap(String ngayLap) {
		this.ngayLap = ngayLap;
	}

}
